###############
# TMUX CONFIG #
###############


set -g default-terminal "screen-256color"
set -s escape-time 0

# Set prefix to control-space
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

bind -n C-k clear-history

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on


# Vim style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Switch session
bind '>' switch-client -n
bind '<' switch-client -p

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# Shift Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

# Kill current session
bind X confirm-before kill-session

# Reload tmux config
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded TMUX Config!"

bind C-Enter command-prompt

# Use Vim keybinds
setw -g mode-keys vi

# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Enable mouse input
set -g mouse on

# Increase scroll limit
set -g history-limit 1000000

###########
# Plugins #
###########

# Automatic plugin manager install

set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.config/tmux/plugins/tpm'

if "test ! -d ~/.config/tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm && ~/.config/tmux/plugins/tpm/bin/install_plugins'"

set -g @plugin 'jdxcode/tmux-spotify-info' # Display current song from Spotify
set -g @plugin 'aaronpowell/tmux-weather' # For displaying weather information in status bar
set -g @plugin 'tmux-plugins/tmux-pain-control' # Better controls for panes
set -g @plugin 'tmux-plugins/tmux-sensible' # Sensible defaults for tmux
set -g @plugin 'tmux-plugins/tmux-yank' # copying to system clipboard
set -g @plugin 'egel/tmux-gruvbox'
# set desired theme options...
set -g @tmux-gruvbox 'dark' # or 'dark256', 'light', 'light256'

# Status Bar
set -g @forecast-location Amsterdam
set -g status-right " #{forecast} | %a %d/%m/%Y %H:%M "
set -g status-right-length 300

# Initialize TMUX plugin manager
run '~/.config/tmux/plugins/tpm/tpm'
